name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: SQLX_OFFLINE=true cargo build --verbose
    - name: Run tests
      run: SQLX_OFFLINE=true cargo test --verbose
